# Generated by Django 3.2.13 on 2022-11-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='time',
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='gender',
            field=models.CharField(choices=[('O', 'OTHERS'), ('F', 'FEMALE'), ('M', 'MALE')], max_length=1),
        ),
        migrations.AlterField(
            model_name='teacherdata',
            name='gender',
            field=models.CharField(choices=[('O', 'OTHERS'), ('F', 'FEMALE'), ('M', 'MALE')], max_length=1),
        ),
        migrations.AlterField(
            model_name='teacherdata',
            name='subject',
            field=models.CharField(choices=[('PHYSICS', 'PHISICS'), ('CHEMISTRY', 'CHEMISTRY'), ('MATHS', 'MATHS')], max_length=20),
        ),
    ]
