# Generated by Django 4.1.3 on 2022-11-07 05:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlineapp', '0002_auto_20221106_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='gender',
            field=models.CharField(choices=[('F', 'FEMALE'), ('O', 'OTHERS'), ('M', 'MALE')], max_length=1),
        ),
        migrations.AlterField(
            model_name='teacherdata',
            name='gender',
            field=models.CharField(choices=[('F', 'FEMALE'), ('O', 'OTHERS'), ('M', 'MALE')], max_length=1),
        ),
        migrations.AlterField(
            model_name='teacherdata',
            name='subject',
            field=models.CharField(choices=[('PHYSICS', 'PHISICS'), ('MATHS', 'MATHS'), ('CHEMISTRY', 'CHEMISTRY')], max_length=20),
        ),
        migrations.CreateModel(
            name='uploadassign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentname', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now=True)),
                ('assignment', models.FileField(upload_to='')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(max_length=100)),
                ('subject', models.CharField(choices=[('PHYSICS', 'PHISICS'), ('MATHS', 'MATHS'), ('CHEMISTRY', 'CHEMISTRY')], max_length=50)),
                ('chap', models.IntegerField(blank=True, null=True)),
                ('topic', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
