# Generated by Django 4.1.3 on 2022-11-07 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineapp', '0003_alter_studentdata_gender_alter_teacherdata_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='subject',
            field=models.CharField(choices=[('CHEMISTRY', 'CHEMISTRY'), ('MATHS', 'MATHS'), ('PHYSICS', 'PHISICS')], max_length=50),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='gender',
            field=models.CharField(choices=[('O', 'OTHERS'), ('M', 'MALE'), ('F', 'FEMALE')], max_length=1),
        ),
        migrations.AlterField(
            model_name='teacherdata',
            name='gender',
            field=models.CharField(choices=[('O', 'OTHERS'), ('M', 'MALE'), ('F', 'FEMALE')], max_length=1),
        ),
        migrations.AlterField(
            model_name='teacherdata',
            name='subject',
            field=models.CharField(choices=[('CHEMISTRY', 'CHEMISTRY'), ('MATHS', 'MATHS'), ('PHYSICS', 'PHISICS')], max_length=20),
        ),
    ]
