# Generated by Django 4.1.3 on 2022-11-07 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineapp', '0004_alter_assignment_subject_alter_studentdata_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='subject',
            field=models.CharField(choices=[('PHYSICS', 'PHISICS'), ('CHEMISTRY', 'CHEMISTRY'), ('MATHS', 'MATHS')], max_length=50),
        ),
        migrations.AlterField(
            model_name='noteupload',
            name='note',
            field=models.FileField(blank=True, null=True, upload_to='notes'),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='gender',
            field=models.CharField(choices=[('O', 'OTHERS'), ('F', 'FEMALE'), ('M', 'MALE')], max_length=1),
        ),
        migrations.AlterField(
            model_name='teacherdata',
            name='gender',
            field=models.CharField(choices=[('O', 'OTHERS'), ('F', 'FEMALE'), ('M', 'MALE')], max_length=1),
        ),
        migrations.AlterField(
            model_name='teacherdata',
            name='subject',
            field=models.CharField(choices=[('PHYSICS', 'PHISICS'), ('CHEMISTRY', 'CHEMISTRY'), ('MATHS', 'MATHS')], max_length=20),
        ),
    ]
