# Generated by Django 3.2.13 on 2022-11-08 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlineapp', '0005_alter_assignment_subject_alter_noteupload_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=100, null=True)),
                ('Ans', models.CharField(max_length=100)),
                ('option_1', models.CharField(max_length=100)),
                ('option_2', models.CharField(max_length=100)),
                ('option_3', models.CharField(max_length=100)),
                ('option_4', models.CharField(max_length=100)),
                ('check', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='assignment',
            name='subject',
            field=models.CharField(choices=[('PHYSICS', 'PHISICS'), ('MATHS', 'MATHS'), ('CHEMISTRY', 'CHEMISTRY')], max_length=50),
        ),
        migrations.AlterField(
            model_name='noteupload',
            name='note',
            field=models.FileField(null=True, upload_to='notes'),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='gender',
            field=models.CharField(choices=[('O', 'OTHERS'), ('M', 'MALE'), ('F', 'FEMALE')], max_length=1),
        ),
        migrations.AlterField(
            model_name='teacherdata',
            name='gender',
            field=models.CharField(choices=[('O', 'OTHERS'), ('M', 'MALE'), ('F', 'FEMALE')], max_length=1),
        ),
        migrations.AlterField(
            model_name='teacherdata',
            name='subject',
            field=models.CharField(choices=[('PHYSICS', 'PHISICS'), ('MATHS', 'MATHS'), ('CHEMISTRY', 'CHEMISTRY')], max_length=20),
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
